### ISSUE TITLE
Agent

### ISSUE THREAD

**Issue by jmerino12** [ayanworks/ARNIMA-flutter-sdk#4]
Hello, I would like to know what Aries agent was used to make this SDK, if it was Faber or Alice, and in what version.

**Comment by ghost** [comment]
Hey, @jmerino12 this is an agent like Alice and can use it as a holder to receive credentials and generate proofs.

**Comment by jmerino12** [comment]
Hi, @sairanjitAW  yeah, However, I find that when you want to make a connection with a mediator agent, it points to a "discover" endpoint and always shows 404 not found.

**Comment by ghost** [comment]
Yes currently we are using the custom mediator for the [ARNIMA-flutter-sdk](https://github.com/ayanworks/ARNIMA-flutter-sdk) soon we are going to implement the mediator coordination protocol which will work with aries based mediator

**Comment by jmerino12** [comment]
could you provide the agent? I find myself doing an experiment, with this library. @sairanjitAW
